name: hprofile-actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: codecheckout
        uses: actions/checkout@v4

      - name: MVN test
        run:  mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle  

      - name: set java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'  

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
   
      - name: SonarQube Scan
        run: sonar-scanner 
            sonar-scanner \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login="08c152ccd325153d25bc09bfdef4c3d3e5a6e6a63" \
            -Dsonar.organization="aravind975code" \
            -Dsonar.projectKey="aravind975code_hprofileproject123" \
            -Dsonar.sources="src/" \
            -Dsonar.junit.reportsPath="target/surefire-reports/" \
            -Dsonar.jacoco.reportsPath="target/jacoco.exec" \
            -Dsonar.java.checkstyle.reportPaths="target/checkstyle-result.xml" \
            -Dsonar.java.binaries="target/test-classes/com/visualpathit/account/controllerTest"
                 