name: hprofile-actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: codecheckout
        uses: actions/checkout@v4

      - name: MVN test
        run:  mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle  

      - name: set java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'  

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
   
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}