name: hprofile-actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: codecheckout
        uses: actions/checkout@v4

      - name: MVN test
        run:  mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle                    